### ISSUE TITLE
Modifying DocType Instruction

### ISSUE THREAD

**Issue by dottenbr** [newmatik/Quality#1]
I would like to have the text editor be invisible when the user opens the instruction. Instead I want to have the field content_preview visible with the content of "content" displayed. When the user clicks the button "edit instruction" I want to show the text editor. Please ask @anandpdoshi for help so you learn how to do this.

**Comment by dottenbr** [comment]
@emakis reminder

**Comment by rmehta** [comment]
Check how its done in note.js: https://github.com/frappe/frappe/blob/develop/frappe/desk/doctype/note/note.js

**Comment by dottenbr** [comment]
Yes, @emakis implement it just like that please.

**Comment by emakis** [comment]
I think I did it just like @rmehta mentioned, please check and comment

**Comment by emakis** [comment]
done, thx to @rmehta and note.js implementation!
