### ISSUE TITLE
Quality User Rights

### ISSUE THREAD

**Issue by dottenbr** [newmatik/Quality#14]
- [x] Assign "Quality User" role to all ESO users
- [x] Assign read rights to all DocTypes in Quality module for "Quality User"
- [x] Remove "Quality Manager" role from all users except for Susanne, Dirk and Me

**Comment by dottenbr** [comment]
@emakis SUPER URGENT

**Comment by emakis** [comment]
Waiting for a working solution https://discuss.erpnext.com/t/new-role-to-all-users/11471
If there isn't then all user roles will be edited one-by-one.

**Comment by emakis** [comment]
The answer was that there isn't way of doing that automatically. Do you want me to do it by hand (one-by-one all users) or can we wait until a solution is implemented?

**Comment by dottenbr** [comment]
Please do it by hand or implement the feature :-)
