### ISSUE TITLE
Instruction Custom Print Format

### ISSUE THREAD

**Issue by dottenbr** [newmatik/Quality#15]
When printing please add the warning text` "<b>Invalid when printed!</b> Attention, this document was printed on 29.03.2016 at 21:32 by Dominik Ottenbreit. Instructions are not valid when printed since they may have been changed from the time of printing. To check out the current and valid version of this instructions please log into newmatik.com > Quality > Instructions > {Instruction Name}."` in English or `"Ungültig wenn ausgedruckt! Achtung, dieses Dokument wurde am 29.03.2015 um 21:32 von Dominik Ottenbreit ausgedruckt. Anweisungen sind ausgedruckt ungültig da sie seit dem Druck verändert worden sein können. Um die aktuelle Version der Anweisung zu lesen logge dich unter newmatik.com > Qualität > Anweisung > {Instruction Name} ein."` for German translation.

Please adjust the print format according to the attached Template.

![new instruction style](https://cloud.githubusercontent.com/assets/9136094/14121329/3dbd2f1a-f5f7-11e5-96cb-a9c00f1fbc8d.png)

**Comment by dottenbr** [comment]
@emakis prioritize without too much stress!

**Comment by dottenbr** [comment]
Also please make sure "INSTRUCTION" translates to "Anweisung" it doesnt at the moment!

**Comment by emakis** [comment]
I think the translation is a matter of the de.cvs file. We will have the right text as soon as we update it. All the other issues is done
