### ISSUE TITLE
Delete DocType Standards and Norms

### ISSUE THREAD

**Issue by dottenbr** [newmatik/Quality#2]
Please delete Standards and Norms but keep Standard or Norm

**Comment by emakis** [comment]
unfortunately only administrators can delete doctypes https://discuss.erpnext.com/t/how-to-delete-a-custom-doctype/8249/5.

I did it locally but not allowed to updat on github... :-/

**Comment by dottenbr** [comment]
I have changed the admin password to the one you know. Log in with user Administrator.

**Comment by emakis** [comment]
done!

**Comment by dottenbr** [comment]
Not done since it is still visible on Newmatic production server!

**Comment by emakis** [comment]
@anandpdoshi when I delete a doctype, this appears again on the next bench update. What am I missing? How can I remove an unused doctype?

**Comment by emakis** [comment]
> when I delete a doctype, this appears again on the next bench update. What am I missing? How can I remove an unused doctype?

Any suggestion here @anandpdoshi, @rmehta ?

**Comment by emakis** [comment]
Physically deleted, but in the newmatik server still was there. So I did a doctype delete in the server, I run bench update and now seems that finally deleted!
