### ISSUE TITLE
New print format for Customer Delighted or Disappointed

### ISSUE THREAD

**Issue by dottenbr** [newmatik/Quality#3]
Please implement this as standard print format for doctype "Customer Delighted or Disappointed"

If customer disappointed please write in red.

![new print format](https://cloud.githubusercontent.com/assets/9136094/12850195/d09fa8a6-cc23-11e5-8a7e-75c69a7cdcf4.png)

**Comment by emakis** [comment]
Please upload to the github the "Customer Delighted or Disappointed" doctype

**Comment by dottenbr** [comment]
If not available on github it is on the newmatik test server and you can push int to github @emakis

**Comment by emakis** [comment]
Hi,
I am in server via ssh. I have gone to the apps/quality directory but git status gives me nothing to upload @dottenbr.

**Comment by emakis** [comment]
Additionaly, I went to the doctypes directory of apps/quality and the doctype Customer Delighted or Disappointed doesn't exist. I can't find where it is

**Comment by dottenbr** [comment]
please ask anand since this must be a thing you run into in the future!

**Comment by emakis** [comment]
@anandpdoshi 
A doctype is created directly in the server http://www.newmatik.com/desk#List/Customer%20Delighted%20or%20Disappointed. Now I am want to take it to work further with it but I am not be able to puch it on the github. In the server (via ssh) and inside quality and newmatik apps, there aren't uncommitted changes as the "git status" says. Any idea how to proceed?

**Comment by anandpdoshi** [comment]
Your server isn’t using developer mode. It isn’t supposed to be for development.

You will need to temporarily set developer_mode: 1 in site config, save the doctype, commit to github.

Best,
Anand Doshi

ERPNext

**Comment by emakis** [comment]
Hi Anand thank you for your quick response. As I get into the site_config.json file under sites/site1.local directory, I saw that the developer_mode attribute already was 1.

**Comment by anandpdoshi** [comment]
Make sure the doctype is not marked as custom and is part of the right module that of your own app

**Comment by dottenbr** [comment]
Makis please make it the default print format for the doctype

**Comment by emakis** [comment]
done
