### ISSUE TITLE
Workflow States for Quality -> Instruction

### ISSUE THREAD

**Issue by dottenbr** [newmatik/Quality#6]
I need:

- Draft
- Approved

I need to be able to reject an approved and have it be a draft again.

**Comment by dottenbr** [comment]
@emakis please prioritize this ASAP

**Comment by emakis** [comment]
I have added a field status with the options draft/approved, I have uploaded to github but I have 2 issues:
1. I cann't pull it in the server. I run ssh, screen -r, bench update and bench start but is shows the old doctype. I did the git status inside app/quality folder but is says no changes
2. In the listview there are 2 status fields: the first is the docstatus and den second is the one I have created. I want to hide the first one but I don't see it in the doctype. Even the topic I have created (https://discuss.erpnext.com/t/hide-docstatus-in-listview/10274) didn't help me. Any suggestion?

**Comment by dottenbr** [comment]
I habe no idea. Can you fix this with Anand?

Am Dienstag, 9. Februar 2016 schrieb Makis :

> I have added a field status with the options draft/approved, I have
> uploaded to github but I have 2 issues:
> 1. I cann't pull it in the server. I run ssh, screen -r, bench update and
> bench start but is shows the old doctype. I did the git status inside
> app/quality folder but is says no changes
> 2. In the listview there are 2 status fields: the first is the docstatus
> and den second is the one I have created. I want to hide the first one but
> I don't see it in the doctype. Even the topic I have created (
> https://discuss.erpnext.com/t/hide-docstatus-in-listview/10274) didn't
> help me. Any suggestion?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newmatik/Quality/issues/6#issuecomment-181810967>.
>


-- 

Mit freundlichen Grüßen / All Best,

*Dominik Ottenbreit*
Geschäftsführer ESO Germany
Director of Business Development

Tel.: ​+49 6752 9112-55
Mobil: ​+49 160 90813466
Fax: ​+49 6752 1524998

www.eso-electronic.com

ESO Electronic Service Ottenbreit GmbH
Hahnenbachstr. 21
55606 Hahnenbach, Germany

Geschaeftsfuehrer (CEO and President): Dominik Ottenbreit
Prokurist (Authorized Signatory):Bjoern Ottenbreit
Gerichtsstand (Jurisdiction): Bad Kreuznach, Germany (HRB 3460)
USt-IdNr. (Tax ID): DE 812 004 832
NCAGE: CH591, DUNS: 314797515, WEEE-Reg-Nr.: DE 84 800 814

**Comment by emakis** [comment]
Please check on newmatik server, if this (or something similar) was what you need

**Comment by dottenbr** [comment]
This does not work! You put status in but it has no effect. The way statuses work can be observed in PCB Specification within Newmatik and there are tutorials about exactly how to do this. If you can not figure it out please ask Frappe how to do it.
